apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template: #This is pod Template
    metadata: #This is pod metadata
      name: javawebapp_pod
      labels:
        app: javawebapp
    spec: #pod specifications
      containers:
      - name: javawebappcontainer #containerName
        image: 132222711585.dkr.ecr.ap-southeast-2.amazonaws.com/java-web-app:VERSION
        ports:
        - containerPort: 8080 #port of the container
          name: 8080portname #we_can_give_name_to_containerport
      imagePullSecrets:
      - name: regcred  
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  selector:
    app: javawebapp #this is pod label
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080 # container port is the target port
    nodePort: 32172
    name: tomcat-httpport
