apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp1
  template: #This is pod Template
    metadata: #This is pod metadata
      name: javawebapp_pod1
      labels:
        app: javawebapp1
    spec: #pod specifications
      containers:
      - name: javawebappcontainer1 #containerName
        image: 132222711585.dkr.ecr.ap-southeast-2.amazonaws.com/java-web-app:VERSION
        ports:
        - containerPort: 8080 #port of the container
          name: 8080portname #we_can_give_name_to_containerport
      imagePullSecrets:
      - name: regcred1  
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc1
  namespace: test-ns
spec:
  selector:
    app: javawebapp1 #this is pod label
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080 # container port is the target port
    nodePort: 32172
    name: tomcat-httpport
